### PR TITLE
'menu is better'

### PR DESCRIPTION
**Pull request by bioshazard**
I simplified the dashboard to just be what it is... menu.

I also moved a bunch of stuff around cuz wysiwyg looked ugly (its a paint brush now)

image

### CODE REVIEW

**Comment by bioshazard** [comment]
was thinking about adding some dropdown functionality

**Comment by wightmike** [comment]
image
Made these updates.

**Comment by wightmike** [comment]
image

**Comment by wightmike** [comment]
image

**Comment by wightmike** [comment]
image

**Comment by wightmike** [comment]
image

**Comment by wightmike** [comment]
https://github.com/eflip/LittlefootCMS/pull/146

**Comment by bioshazard** [comment]
love it

**Pull request closed without merging**
